version: '3'
services:
    cluster/mongo-1-2:
        container_name: "cluster/mongo-1-2"
        image: mongo:4.0.1
        ports:
            - "30012:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        restart: always

    cluster/mongo-1-3:
        container_name: "cluster/mongo-1-3"
        image: mongo:4.0.1
        ports:
            - "30013:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    cluster/mongo-1-1:
        container_name: "cluster/mongo-1-1"
        image: mongo:4.0.1
        ports:
            - "30011:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        links:
            - cluster/mongo-1-2:cluster/mongo-1-2
            - cluster/mongo-1-3:cluster/mongo-1-3
        restart: always

    mongo-rs1-setup:
        container_name: "mongo-rs1-setup"
        image: mongo:4.0.1
        depends_on:
            - "cluster/mongo-1-1"
            - "cluster/mongo-1-2"
            - "cluster/mongo-1-3"
        links:
            - cluster/mongo-1-1:cluster/mongo-1-1
            - cluster/mongo-1-2:cluster/mongo-1-2
            - cluster/mongo-1-3:cluster/mongo-1-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=cluster/mongo-1-1
            - MONGO2=cluster/mongo-1-2
            - MONGO3=cluster/mongo-1-3
            - RS=rs1
        entrypoint: [ "/scripts/setup.sh" ]

        
