version: '3'
services:
    cluster/mongo-cnf-2:
        container_name: "cluster/mongo-cnf-2"
        image: mongo:4.0.1
        ports:
            - "30102:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        restart: always

    cluster/mongo-cnf-3:
        container_name: "cluster/mongo-cnf-3"
        image: mongo:4.0.1
        ports:
            - "30103:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    cluster/mongo-cnf-1:
        container_name: "cluster/mongo-cnf-1"
        image: mongo:4.0.1
        ports:
            - "30101:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        links:
            - cluster/mongo-cnf-2:cluster/mongo-cnf-2
            - cluster/mongo-cnf-3:cluster/mongo-cnf-3
        restart: always

    mongo-cnf-setup:
        container_name: "mongo-cnf-setup"
        image: mongo:4.0.1
        depends_on:
            - "cluster/mongo-cnf-1"
            - "cluster/mongo-cnf-2"
            - "cluster/mongo-cnf-3"
        links:
            - cluster/mongo-cnf-1:cluster/mongo-cnf-1
            - cluster/mongo-cnf-2:cluster/mongo-cnf-2
            - cluster/mongo-cnf-3:cluster/mongo-cnf-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=cluster/mongo-cnf-1
            - MONGO2=cluster/mongo-cnf-2
            - MONGO3=cluster/mongo-cnf-3
            - RS=cnf-serv
            - PORT=27017
        entrypoint: [ "/scripts/setup-cnf.sh" ]
