version: '3'
services:
    clustermongo-router:
        container_name: "clustermongo-router"
        image: mongo:4.0.1
        ports:
            - "30001:27017"
        depends_on:
            - "mongo-rs1-setup"
            - "mongo-rs2-setup"
            - "mongo-cnf-setup"
        external_links:
            - clustermongo-cnf-1:clustermongo-cnf-1
            - clustermongo-cnf-2:clustermongo-cnf-2
            - clustermongo-cnf-3:clustermongo-cnf-3
            - clustermongo-1-1:clustermongo-1-1
            - clustermongo-1-2:clustermongo-1-2
            - clustermongo-1-3:clustermongo-1-3
            - clustermongo-2-1:clustermongo-2-1
            - clustermongo-2-2:clustermongo-2-2
            - clustermongo-2-3:clustermongo-2-3
        command: mongos --configdb cnf-serv/clustermongo-cnf-1:27017,clustermongo-cnf-2:27017,clustermongo-cnf-3:27017 --port 27017 --bind_ip 0.0.0.0
        restart: always

    clustermongo-shard-setup:
        container_name: "clustermongo-shard-setup"
        image: mongo:4.0.1
        depends_on:
            - "clustermongo-router"
        links:
            - clustermongo-router:clustermongo-router
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGOS=clustermongo-router
            - MONGO11=clustermongo-1-1
            - MONGO12=clustermongo-1-2
            - MONGO13=clustermongo-1-3
            - MONGO21=clustermongo-2-1
            - MONGO22=clustermongo-2-2
            - MONGO23=clustermongo-2-3
            - RS1=rs1
            - RS2=rs2
            - PORT=27017
            - PORT1=27017
            - PORT2=27017
            - PORT3=27017
        entrypoint: [ "/scripts/init-shard.sh" ]
        restart: on-failure:20
