version: '3'
services:
    clustermongo-2-1:
        container_name: "clustermongo-2-1"
        image: mongo:4.0.1
        ports:
            - "30022:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        restart: always

    clustermongo-2-3:
        container_name: "clustermongo-2-3"
        image: mongo:4.0.1
        ports:
            - "30023:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    clustermongo-2-2:
        container_name: "clustermongo-2-1"
        image: mongo:4.0.1
        ports:
            - "30021:27017"
        command: mongod --replSet rs2 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        links:
            - clustermongo-2-1:clustermongo-2-1
            - clustermongo-2-3:clustermongo-2-3
        restart: always

    mongo-rs2-setup:
        container_name: "mongo-rs2-setup"
        image: mongo:4.0.1
        depends_on:
            - "clustermongo-2-1"
            - "clustermongo-2-2"
            - "clustermongo-2-3"
        links:
            - clustermongo-2-1:clustermongo-2-1
            - clustermongo-2-1:clustermongo-2-2
            - clustermongo-2-3:clustermongo-2-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=clustermongo-2-1
            - MONGO2=clustermongo-2-2
            - MONGO3=clustermongo-2-3
            - RS=rs2
        entrypoint: [ "/scripts/setup.sh" ]

        
