version: '3'
services:
    cluster/mongo-router:
        container_name: "cluster/mongo-router"
        image: mongo:4.0.1
        ports:
            - "30001:27017"
        depends_on:
            - "mongo-rs1-setup"
            - "mongo-rs2-setup"
            - "mongo-cnf-setup"
        external_links:
            - cluster/mongo-cnf-1:cluster/mongo-cnf-1
            - cluster/mongo-cnf-2:cluster/mongo-cnf-2
            - cluster/mongo-cnf-3:cluster/mongo-cnf-3
            - cluster/mongo-1-1:cluster/mongo-1-1
            - cluster/mongo-1-2:cluster/mongo-1-2
            - cluster/mongo-1-3:cluster/mongo-1-3
            - cluster/mongo-2-1:cluster/mongo-2-1
            - cluster/mongo-2-1:cluster/mongo-2-1
            - cluster/mongo-2-3:cluster/mongo-2-3
        command: mongos --configdb cnf-serv/cluster/mongo-cnf-1:27017,cluster/mongo-cnf-2:27017,cluster/mongo-cnf-3:27017 --port 27017 --bind_ip 0.0.0.0
        restart: always

    cluster/mongo-shard-setup:
        container_name: "cluster/mongo-shard-setup"
        image: mongo:4.0.1
        depends_on:
            - "cluster/mongo-router"
        links:
            - cluster/mongo-router:cluster/mongo-router
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGOS=cluster/mongo-router
            - MONGO11=cluster/mongo-1-1
            - MONGO12=cluster/mongo-1-2
            - MONGO13=cluster/mongo-1-3
            - MONGO21=cluster/mongo-2-1
            - MONGO22=cluster/mongo-2-1
            - MONGO23=cluster/mongo-2-3
            - RS1=rs1
            - RS2=rs2
            - PORT=27017
            - PORT1=27017
            - PORT2=27017
            - PORT3=27017
        entrypoint: [ "/scripts/init-shard.sh" ]
        restart: on-failure:20
