version: '3'
services:
    clustermongo-cnf-2:
        container_name: "clustermongo-cnf-2"
        image: mongo:4.0.1
        ports:
            - "30102:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        restart: always

    clustermongo-cnf-3:
        container_name: "clustermongo-cnf-3"
        image: mongo:4.0.1
        ports:
            - "30103:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    clustermongo-cnf-1:
        container_name: "clustermongo-cnf-1"
        image: mongo:4.0.1
        ports:
            - "30101:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        links:
            - clustermongo-cnf-2:clustermongo-cnf-2
            - clustermongo-cnf-3:clustermongo-cnf-3
        restart: always

    mongo-cnf-setup:
        container_name: "mongo-cnf-setup"
        image: mongo:4.0.1
        depends_on:
            - "clustermongo-cnf-1"
            - "clustermongo-cnf-2"
            - "clustermongo-cnf-3"
        links:
            - clustermongo-cnf-1:clustermongo-cnf-1
            - clustermongo-cnf-2:clustermongo-cnf-2
            - clustermongo-cnf-3:clustermongo-cnf-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=clustermongo-cnf-1
            - MONGO2=clustermongo-cnf-2
            - MONGO3=clustermongo-cnf-3
            - RS=cnf-serv
            - PORT=27017
        entrypoint: [ "/scripts/setup-cnf.sh" ]
